### PR TITLE
Some updates to help things along

### PR DESCRIPTION
**Pull request by feilipu**

### CODE REVIEW

**Comment by feilipu** [comment]
I am really struggling with this one. The code is working perfectly on a RC2014 and Digital I/O board.
But, it is not working on my SC130. I do not know why.

Going to need some time to think this through.
Thought it might be weak power via the USB adaptor. But no cigar.

**Review by cyrusbuilt — APPROVED** [review]
This all seems reasonable to me. I will test this on actual hardware.  I was not aware of __sfr. Thanks for the info! And thanks for taking the time to look into this!

**Comment by feilipu** [comment]
Thanks. Do let me know if it is working on hardware.

I've still no idea why my sc130 plus digital I/O aren't working. So your reference is very interesting.

**Comment by feilipu** [comment]
Just to close off on this. I confirmed with Stephen that his devices were working so then it was just working out what was different. Being, I was running at 36MHz configuration. This is too fast for the diode based address qualification on Spencer's DIO Module to work.

Either running at standard 18MHz or adding total 3 I/O Wait States (update 4 I/O Wait needed for Input to function correctly) in the configuration solves the problem. Now, we're on the same page. Screenshot from functioning Spencer Digital IO configuration below.

Screenshot from 2022-08-05 19-49-05

**Pull request merged**
